
# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
# alt-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'


# too slow
cmd-e = '''
exec-and-forget open -na "Ghostty" --args --command=yazi \
    --quit-after-last-window-closed \
    --macos-icon=retro \
    --title=yazi
'''
